WELCOME_MESSAGE = "Добро пожаловать! Пожалуйста, зарегистрируйтесь, чтобы продолжить."
REGISTRATION_NAME = "Введите ваше имя:"
REGISTRATION_AGE = "Введите ваш возраст (от 12 до 25):"
REGISTRATION_SUCCESS = "Регистрация успешно завершена!"
POST_MESSAGE = "Напишите ваш пост:"
POST_SUCCESS = "Ваш пост успешно опубликован!"
VOLUNTEER_LINK = "Ссылка на форму для волонтеров: https://forms.gle/..."
PSYCHOLOGIST_LINK = "Свяжитесь с психологом: @username"